# Generated by Django 5.2.11 on 2026-03-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datatable",
            name="date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="datatable",
            name="name",
            field=models.CharField(max_length=49),
        ),
    ]
